---
title: "preliminary_analysis"
Author: "Geoffrey Jing and Ryosuke Mega"
output: html_document
---

Preliminary Data Loading

```{r}
library(googlesheets4)
library(tidyverse)
library(patchwork)
library(ggthemes)
gs4_auth()
```

```{r}
sheet_url <- "https://docs.google.com/spreadsheets/d/14Qx-K3Q7ih31Xlq6viIY_CNBGaTi7b1dZFdgj5BKiYk"
falls_creek_park <- read_sheet(sheet_url, col_types = "c")
colnames(falls_creek_park)
falls_creek_park <- falls_creek_park %>%
  mutate(Timestamp = gsub("\n", " ", Timestamp),
         Timestamp = as.POSIXct(Timestamp, format = "%m/%d/%Y %H:%M:%S"))
#str(falls_creek_park)
```


```{r}
sheet_url <- "https://docs.google.com/spreadsheets/d/1DYf9GIkIHNRmVmpiz8NvM7-Y05Fj4FNiNhO4beoPwXo"
velzke_park <- read_sheet(sheet_url, col_types = "c")
colnames(velzke_park)
velzke_park <- velzke_park %>%
  mutate(Timestamp = gsub("\n", " ", Timestamp),
         Timestamp = as.POSIXct(Timestamp, format = "%m/%d/%Y %H:%M:%S"))
#str(velzke_park)
```

```{r}
sheet_url <- "https://docs.google.com/spreadsheets/d/1E6IaEsva8njQ0jSNdOzquGCZq1cNdgugaJb_Kto050A"
shager_park <- read_sheet(sheet_url, col_types = "c")
colnames(shager_park)
shager_park <- shager_park %>%
  mutate(Timestamp = gsub("\n", " ", Timestamp),
         Timestamp = as.POSIXct(Timestamp, format = "%m/%d/%Y %H:%M:%S"))
#str(shager_park)
# shager_park %>%
#   filter(!inherits(`Timestamp`, "POSIXct"))
```

```{r}
sheet_url <- "https://docs.google.com/spreadsheets/d/1PT7vfE_qcSpi1mcYf1cAI0l9sRPNRqkrWpHFeRyl7uQ"
ackman_park <- read_sheet(sheet_url, col_types = "c")
colnames(ackman_park)
ackman_park <- ackman_park %>%
  mutate(Timestamp = gsub("\n", " ", Timestamp),
         Timestamp = as.POSIXct(Timestamp, format = "%m/%d/%Y %H:%M:%S"))
#str(ackman_park)
```

```{r}
sheet_url <- "https://docs.google.com/spreadsheets/d/1DzORfuDsQbyJQM6hNuhY_UOLRvPoCKfZhwrhAYWlgIw"
albers_park <- read_sheet(sheet_url, col_types = "c")
colnames(albers_park)
albers_park <- albers_park %>%
  mutate(Timestamp = gsub("\n", " ", Timestamp),
         Timestamp = as.POSIXct(Timestamp, format = "%m/%d/%Y %H:%M:%S"))
#str(albers_park)
```

```{r}
sheet_url <- "https://docs.google.com/spreadsheets/d/10F0vnMuTaBH2WmgfZ7ULDLqm8em2pyHR5i2H5BGUj84"
cannon_rvr_wildness_area_all <- read_sheet(sheet_url, col_types = "c")
colnames(cannon_rvr_wildness_area_all)
cannon_rvr_wildness_area_all <- cannon_rvr_wildness_area_all %>%
  mutate(Timestamp = gsub("\n", " ", Timestamp),
         Timestamp = as.POSIXct(Timestamp, format = "%m/%d/%Y %H:%M:%S"))
#str(cannon_rvr_wildness_area_all)
```

```{r}
sheet_url <- "https://docs.google.com/spreadsheets/d/14reTrAk2w0lb5_1cCyayXhqLNmD9GBJ7UhqP9pIXBeE"
caron_park <- read_sheet(sheet_url, col_types = "c")
colnames(caron_park)
caron_park <- caron_park %>%
  mutate(Timestamp = gsub("\n", " ", Timestamp),
         Timestamp = as.POSIXct(Timestamp, format = "%m/%d/%Y %H:%M:%S"))
#str(caron_park)
```

```{r}
sheet_url <- "https://docs.google.com/spreadsheets/d/1nas8nQvkhEzKg-IRwyfdF_ohRv9LRWBnPej8XYxcv_E"
circle_lake_park <- read_sheet(sheet_url, col_types = "c")
colnames(caron_park)
circle_lake_park <- circle_lake_park %>%
  mutate(Timestamp = gsub("\n", " ", Timestamp),
         Timestamp = as.POSIXct(Timestamp, format = "%m/%d/%Y %H:%M:%S"))
#str(circle_lake_park)
```

```{r}
sheet_url <- "https://docs.google.com/spreadsheets/d/1voDUBr8AE8nS6Uz9PS4HrtJxrNRpgT3JcxEtzMGsUC8"
hirdler_park <- read_sheet(sheet_url, col_types = "c")
colnames(hirdler_park)
hirdler_park <- hirdler_park %>%
  mutate(Timestamp = gsub("\n", " ", Timestamp),
         Timestamp = as.POSIXct(Timestamp, format = "%m/%d/%Y %H:%M:%S"))
#str(hirdler_park)
```

```{r}
sheet_url <- "https://docs.google.com/spreadsheets/d/1HVckFwhwWVk7BuPQKdVk4F-AUQCl66aKxsqzpszGmD8"
kalina_park <- read_sheet(sheet_url, col_types = "c")
colnames(kalina_park)
kalina_park <- kalina_park %>%
  mutate(Timestamp = gsub("\n", " ", Timestamp),
         Timestamp = as.POSIXct(Timestamp, format = "%m/%d/%Y %H:%M:%S"))
#str(kalina_park)
```

```{r}
sheet_url <- "https://docs.google.com/spreadsheets/d/1e6Fn2KHVF_dlx9o1SRJMWvVwLvObQUCPWvwS6QsavWA"
king_mill_park <- read_sheet(sheet_url, col_types = "c")
colnames(king_mill_park)
king_mill_park <- king_mill_park %>%
  mutate(Timestamp = gsub("\n", " ", Timestamp),
         Timestamp = as.POSIXct(Timestamp, format = "%m/%d/%Y %H:%M:%S"))
#str(king_mill_park)
```

```{r}
sheet_url <- "https://docs.google.com/spreadsheets/d/1ImLrM5gGGqJdPaLdne5upCe2z1G6VDLY4bBvvvVqo_o"
mccullough_park <- read_sheet(sheet_url, col_types = "c")
colnames(king_mill_park)
mccullough_park <- mccullough_park %>%
  mutate(Timestamp = gsub("\n", " ", Timestamp),
         Timestamp = as.POSIXct(Timestamp, format = "%m/%d/%Y %H:%M:%S"))
#str(mccullough_park)
```

```{r}
save(ackman_park, file = "ackman_park.rda")
save(albers_park, file = "albers_park.rda")
save(cannon_rvr_wildness_area_all, file = "cannon_rvr_wildness_area_all.rda")
save(caron_park, file = "caron_park.rda")
save(circle_lake_park, file = "circle_lake_park.rda")
save(falls_creek_park, file = "falls_creek_park.rda")
save(hirdler_park, file = "hirdler_park.rda")
save(kalina_park, file = "kalina_park.rda")
save(king_mill_park, file = "king_mill_park.rda")
save(mccullough_park, file = "mccullough_park.rda")
save(shager_park, file = "shager_park.rda")
save(velzke_park, file = "velzke_park.rda")
```

```{r}
park_all <- rbind(ackman_park, albers_park, cannon_rvr_wildness_area_all, caron_park, circle_lake_park, falls_creek_park, hirdler_park, kalina_park, king_mill_park, mccullough_park, shager_park, velzke_park)
```

```{r}
library(dplyr)
library(lubridate)

park_all <- park_all %>%
  mutate(
    Year = year(Timestamp),
    Month = month(Timestamp, label = TRUE),  # Month as abbreviated name (Jan, Feb, etc.)
    Weekday = wday(Timestamp, label = TRUE), # Weekday as abbreviated name (Sun, Mon, etc.)
    Hour = hour(Timestamp)
  )

park_all <- park_all %>%
  mutate(
    `Park Name` = case_when(
      str_detect(Location, "3732") ~ "Velzke Park",
      str_detect(Location, "2239") ~ "Shager Park",
      str_detect(Location, "14398") ~ "Mccullough Park",
      str_detect(Location, "2100") ~ "King Mill Park",
      str_detect(Location, "11442") ~ "Kalina Park",
      str_detect(Location, "15100") ~ "Hirdler Park",
      str_detect(Location, "2050") ~ "Falls Creek Park",
      str_detect(Location, "4560") ~ "Circle Lake Park",
      str_detect(Location, "6816") ~ "Caron Park",
      str_detect(Location, "8662") ~ "Albers Park",
      str_detect(Location, "4080") ~ "Ackman Park",
      str_detect(Location, "3471|13996") ~ "Cannon River Wilderness Area Park"
    )
  )
head(park_all)
save(park_all, file = "park_all.rda")
```

```{r}
# can see which values have null for park names, might want to clean this later
null_vals <- park_all %>% filter(is.na(`Park Name`))
```


```{r}
library(stringr)
library(dplyr)

park_all$`Call Type` <- str_replace_all(park_all$`Call Type`, "\n", " ")
park_all$`Call Type` <- str_replace_all(park_all$`Call Type`, "  ", " ")


park_all <- park_all %>%
  mutate(check_extra_other = case_when(`Call Type` == "Park Check" ~ "Park Check", 
                                       `Call Type`== "Extra Patrol" ~ "Extra Patrol",
                                       is.na(`Call Type`) ~ NA,
                                       TRUE ~ "Other"))
```

```{r}
# add day of week variable
park_all <- park_all %>%
  mutate(`Day Type` = case_when(
    Weekday %in% c("Mon", "Tue", "Wed", "Thu") ~ "Weekday",
    Weekday == "Fri" ~ "Fri",
    Weekday %in% c("Sat", "Sun") ~ "Weekend"
  )
  )
```

```{r}
park_all <- park_all %>%
  mutate(Season = case_when(Month == "Dec" | Month == "Jan" | Month == "Feb" ~ "Winter", 
                            Month == "Mar" | Month == "Apr" | Month == "May" ~ "Spring",
                            Month == "Jun" | Month == "Jul" | Month == "Aug"~ "Summer",
                            Month == "Sep" | Month == "Oct" | Month == "Nov" ~ "Autumn",
                            is.na(Month) ~ NA,
                            TRUE ~ "Other"))
```

